### ISSUE TITLE
Update pymoskito wip_laborpr

### ISSUE THREAD

**Issue by gruberth** [umit-iace/pymoskito#2]
It would be nice if the following features from pywisp could also be available in pymoskito:
- [ ] choosing the visualization in the .sreg file
- [x] the new plotting features like autoselection of newly added plots
- [ ] show the icons in the menu bar in correct size on high resolution screens
- [x] the pinned default docks

**Comment by TanDro** [comment]
1.: That is not that easy to integrate like in pywisp. I have added a exception handling, to avoid a crash.
3.: You can add os.environ['QT_AUTO_SCREEN_SCALE_FACTOR'] = "1" in the main.py to enable the correct scaling.
