### ISSUE TITLE
wip_laborpr binding test on windows

### ISSUE THREAD

**Issue by gruberth** [umit-iace/pymoskito#3]
I have tested the ballintube/ba_gruber simulation on a windows system (MECHLB05) in the laboratory.
Before I ran the sim i did the following steps:
1. Made a new venv called imw_test
2. Installed the actual wip_laborpr branch of pymoskito with `python setup.py install`
3. Fixed the problem with pyqt5-sip

Pymoskito started, simulation of a regime started and also cmake started but stopped because of the exeption `Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)`, so the generation of binding config failed.

**Comment by simbach** [comment]
I have added the environmental variable PYTHON_LIBRARY=<path> then it worked with pymoskito.
From command line it worked also without this declaration???

**Comment by simbach** [comment]
An error arises when library should be loaded
`AttributeError: 'NoneType' object has no attribute 'loader'` because `spec = None`.

**Comment by TanDro** [comment]
@gruberth @simbach last commit aaa946f3d2c849f2eba3d42e9cd5cf8e0f11d5fb runs on my arch linux and with windows 10. Please can you verify.

**Comment by simbach** [comment]
I tested successfully on windows 8.1 + Cmake from Visual Studio 2017:
- the "tanksystem" example of pymoskito
- the ba_gruber ball in tube simulation with a additional define in Trajectory.h a1ab5e5
Adittional environment variable:
- PYTHON_LIBRARY - C:/WPy-3670/python-3.6.7.amd64/libs/python36.lib

**Comment by simbach** [comment]
is also working on surface.
@gruberth if its still not working please check if 
- PYTHON_EXECUTABLE:
- PYTHON_INCLUDE_DIR:
- PYTHON_LIBRARY:
are well defined in CMakeChache.txt are found.

**Comment by simbach** [comment]
to avoid problems using cmake
- the winpython script register_python.bat or register_python_for_all.bat should be run
- no PYTHONPATH environment variable should exist which points to another/older python
- no additional environment variables have to be defined
